spring:
  application:
    name: backend
  
  # Profile padrão para desenvolvimento/testes
  profiles:
    active: default
  
  # Configurações do H2 Database (desenvolvimento/testes)
  datasource:
    url: jdbc:h2:mem:todolist
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # Configurações do JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Console do H2 (para desenvolvimento)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Configuração de formatação JSON
  jackson:
    date-format: dd-MM-yyyy HH:mm:ss
    time-zone: America/Sao_Paulo

# Configurações do servidor
server:
  port: 8080

# Configurações de logging
logging:
  level:
    com.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE